# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'be-you' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for be-you
  pod 'SwiftLint'

  target 'be-youTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'be-youUITests' do
    # Pods for testing
  end

end
